### ISSUE TITLE
error: 'Namespace' object has no attribute 'flash_method'

### ISSUE THREAD

**Issue by raingloom** [postmarketOS/pmbootstrap#1527]
I ran `pmbootstrap export --odin` and this is what I got:

full log:

```
(010625) [01:36:28] (rootfs_samsung-maguro) calculate depends of device-samsung-maguro (pmbootstrap -v for details)
(010625) [01:36:34] (rootfs_samsung-maguro) install
(010625) [01:36:34] (rootfs_samsung-maguro) % apk --no-progress add -u --virtual .pmbootstrap mesa-dri-swrast mesa-glapi mesa-gl
(1/1) Installing .pmbootstrap (0)
OK: 237 MiB in 241 packages
(010625) [01:36:35] (rootfs_samsung-maguro) % apk --no-progress add device-samsung-maguro
OK: 237 MiB in 241 packages
(010625) [01:36:37] (rootfs_samsung-maguro) % apk --no-progress del .pmbootstrap
(1/1) Purging .pmbootstrap (0)
OK: 237 MiB in 240 packages
(010625) [01:36:39] (rootfs_samsung-maguro) calculate depends of postmarketos-mkinitfs (pmbootstrap -v for details)
(010625) [01:36:39] (rootfs_samsung-maguro) install
(010625) [01:36:39] (rootfs_samsung-maguro) % apk --no-progress add -u --virtual .pmbootstrap mesa-gl mesa-glapi
(1/1) Installing .pmbootstrap (0)
OK: 237 MiB in 241 packages
(010625) [01:36:41] (rootfs_samsung-maguro) % apk --no-progress add postmarketos-mkinitfs
OK: 237 MiB in 241 packages
(010625) [01:36:43] (rootfs_samsung-maguro) % apk --no-progress del .pmbootstrap
(1/1) Purging .pmbootstrap (0)
OK: 237 MiB in 240 packages
(010625) [01:36:45] (rootfs_samsung-maguro) calculate depends of  (pmbootstrap -v for details)
(010625) [01:36:45] (rootfs_samsung-maguro) mkinitfs samsung-maguro
(010625) [01:36:45] (rootfs_samsung-maguro) % mkinitfs -o /boot/initramfs-samsung-maguro 3.0.31-cyanogenmod
==> initramfs: creating /boot/initramfs-samsung-maguro
Scanning kernel module dependencies...
NOTE: ** modprobe warnings below can be ignored ** if your device does not run the
mainline kernel yet (most devices!) or if the related kernel options are enabled
with 'y' instead of 'm' (module).
modprobe: WARNING: Module drm_kms_helper not found in directory /lib/modules/3.0.31-cyanogenmod
modprobe: WARNING: Module drm not found in directory /lib/modules/3.0.31-cyanogenmod
modprobe: WARNING: Module dm_crypt not found in directory /lib/modules/3.0.31-cyanogenmod
==> initramfs: creating boot.img
==> initramfs: creating /boot/initramfs-samsung-maguro-extra
(010625) [01:36:51] Export symlinks to: /tmp/postmarketOS-export
(010625) [01:36:51] ERROR: 'Namespace' object has no attribute 'flash_method'
(010625) [01:36:51] See also: <https://postmarketos.org/troubleshooting>
(010625) [01:36:51] Traceback (most recent call last):
  File "/home/rain/pmbootstrap/pmb/__init__.py", line 61, in main
    getattr(frontend, args.action)(args)
  File "/home/rain/pmbootstrap/pmb/helpers/frontend.py", line 187, in export
    pmb.export.frontend(args)
  File "/home/rain/pmbootstrap/pmb/export/frontend.py", line 31, in frontend
    pmb.export.odin(args, flavor, target)
  File "/home/rain/pmbootstrap/pmb/export/odin.py", line 34, in odin
    pmb.flasher.init(args)
  File "/home/rain/pmbootstrap/pmb/flasher/init.py", line 26, in init
    method = args.flash_method or args.deviceinfo["flash_method"]
AttributeError: 'Namespace' object has no attribute 'flash_method'
```
looks like a Python thing

**Comment by MartijnBraam** [comment]
Looks like we have introduced a regression in b29cc877a74874973cd4f4795d57b766dad65318 and nobody used `--odin` since.

Since the export command used to be a part of `pmbootstrap flasher` it always had a `flash_method` attribute from `--method`. This is no longer the case since `pmbootstrap flasher export` is moved to `pmbootstrap export`
